#!/usr/bin/python3

# function to raise an exception with message


def raise_exception_msg(message=""):
    raise NameError(message)
